### ISSUE TITLE
Bad resource packaging

### ISSUE THREAD

**Issue by rberenguel** [rberenguel/bear-note-graph#1]
```
Traceback (most recent call last):
    File "/Users/user/Library/Python/3.7/lib/python/site-packages/bear_note_graph/settings.py", line 13, in default_palettes
    with open(RESOURCES / Path("palettes.yaml"), "r") as data:
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/Library/Python/3.7/lib/python/site-packages/resources/palettes.yaml'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
    File "/Users/user/Library/Python/3.7/bin/bear-note-graph", line 5, in <module>
    from bear_note_graph.main import main
    File "/Users/user/Library/Python/3.7/lib/python/site-packages/bear_note_graph/main.py", line 10, in <module>
    from .settings import (
    File "/Users/user/Library/Python/3.7/lib/python/site-packages/bear_note_graph/settings.py", line 19, in <module>
    PALETTES = default_palettes()
    File "/Users/user/Library/Python/3.7/lib/python/site-packages/bear_note_graph/settings.py", line 16, in default_palettes
    raise Exception(f"Could not load the YAML file: {exc}")
    Exception: Could not load the YAML file: [Errno 2] No such file or directory: '/Users/user/Library/Python/3.7/lib/python/site-packages/resources/palettes.yaml'
```

**Comment by rberenguel** [comment]
Fixed in release 0.1.2
