### ISSUE TITLE
sfdp: command not found

### ISSUE THREAD

**Issue by ValentinWalter** [rberenguel/bear-note-graph#5]
0.1.9
```
INFO - Copying Bear database to /tmp/BearExportTemp.sqlite
INFO - Fetching notes from (the copy of the) database
INFO - Fetched 340 notes from the (copy of) the Bear database
WARNING - Skipping empty note: bear://x-callback-url/open-note?id=[UUID]
WARNING - Skipping empty note: bear://x-callback-url/open-note?id=[UUID]
WARNING - Could not find note titled <<Title>> linked from note bear://x-callback-url/open-note?id=[UUID]
INFO - All notes processed, there are 85 tags, 340 (valid) notes, 349 tag edges among them and 401 note edges among them
INFO - Graphviz file generated at /tmp/bear_graph.gv
INFO - Running Graphviz command "sfdp -Tpdf /tmp/bear_graph.gv > /tmp/bear_graph.pdf"
/bin/sh: sfdp: command not found
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/bear-note-graph", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bear_note_graph/main.py", line 124, in main
    generate_graph(graph_format)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bear_note_graph/generate.py", line 54, in generate_graph
    run_graphviz(graph_format)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bear_note_graph/generate.py", line 213, in run_graphviz
    subprocess.run(command, shell=True, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sfdp -Tpdf /tmp/bear_graph.gv > /tmp/bear_graph.pdf' returned non-zero exit status 127.
```

**Comment by ValentinWalter** [comment]
Oh my god, I just went over the README again and found out about the [Installing Graphviz](https://github.com/rberenguel/bear-note-graph#installing-graphviz) part. I figured it might have been something like this, but a quick search for "sfdp" didn't turn up anything.

**Comment by rberenguel** [comment]
Oh don't worry, I added it to the readme in version 0.1.3 or so, you may have never seen it. Let me know how the graph looks!
